database seed.js file code review
HR-Mega-Bites/cooking-service pull request #6
Opened 2018-04-16 23:59 UTC by HourglassMagi

Please review this pull request for me. let me know if there are any significant changes I need to make, including but not limited to adhering to style guide rules. Thank you.

2018-04-16 23:59 UTC, HourglassMagi commented
![](https://github.trello.services/images/mini-trello-icon.png) [PR Laurent's database seed branch seed.js file.](https://trello.com/c/W8RkSwUK/36-pr-laurents-database-seed-branch-seedjs-file)

2018-04-17 01:50 UTC, CareyL96 commented on database/seed.js
> +    }
looks like this indentation should not be indented

2018-04-17 01:52 UTC, CareyL96 commented on database/seed.js
> +  const steps = Math.floor(Math.random() * 15) + 4;
missing indentation in this for loop

2018-04-17 01:58 UTC, careyl96 requested changes
fix indentation issues, add a space after the while loop (I also think it should be a for loop, not a while loop; while loops are generally used to repeat a section of code an unknown number of times), and consider renaming the createFakeData function to insertFakeData.

2018-04-17 21:44 UTC, HourglassMagi commented
Hey @CareyL96 ,
Thanks for the feedback. I made the requested changes. I decided to keep the while loop because I don't know how many steps there will be for a given recipe. They are being randomly generated between 4 and 15 which is why I decided to user a while loop instead of a for loop. Let me know if you see any other changes I need to make. Thanks.

2018-04-17 23:12 UTC, careyl96 submitted a review, later dismissed
Missing indentation at the while loop, jsonObj, and text variable initializations since they're all nested within the for loop but you can fix that in the next PR. Consider changing steps to numSteps instead. Looks good otherwise!

2018-04-18 02:49 UTC, merged